### ISSUE TITLE
Not working in netbeans 11

### ISSUE THREAD

**Issue by sks40gb** [jkan997/SlingBeans#20]

**Comment by badvision** [comment]
Works in my install of Netbeans 11.  I'm using Windows 10.  Can you provide more detail about what is not working?

**Comment by badvision** [comment]
Oh scratch that.  I installed a new version of NB 11.1 and now the plugin won't install because:
`The plugin org.jdesktop.layout is requested in version 1.24.1.`

I added the Netbeans 8.2 community portal to update center: http://plugins.netbeans.org/nbpluginportal/updates/8.2/catalog.xml.gz  and it was able to find the "Swing Layout Extensions integration" module which includes this dependency.

**Comment by jkan997** [comment]
Thanks @badvision for finding out! Probably this org.jdesktop.layout should just be bundled in NBM to be used in NB 9.

**Comment by jkan997** [comment]
Issue fixed - SlingBeans are now working in most recent version of Apache NetBeans (12.1)
